name: Build APK

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Install buildozer
      run: |
        pip install cython buildozer
    - name: Build APK
      run: |
        buildozer init
        buildozer android debug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
